# Generated by Django 2.0.4 on 2018-04-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstracttools',
            old_name='output_value',
            new_name='indicator',
        ),
        migrations.AddField(
            model_name='diamond',
            name='condition',
            field=models.CharField(choices=[('1', '>'), ('2', '<'), ('3', '=')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diamond',
            name='pam1',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diamond',
            name='pam2',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='steps',
            name='workflow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbs.Workflow'),
        ),
    ]
