# Generated by Django 2.0.4 on 2018-04-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0002_auto_20180407_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps',
            name='workflow_id',
        ),
        migrations.AddField(
            model_name='steps',
            name='workflow_id',
            field=models.ManyToManyField(to='dbs.Workflow'),
        ),
    ]
